#!/usr/bin/env python3
"""Emit a tt-buddy-style bound-class report for one iter directory.

Inputs (all under <iter_dir>):
  metrics.json
    .stage_medians       — per-pipeline-stage wall ms (project/tile_assign/sort/blend/total)
    .sub_medians         — per-sub-stage wall ms (project.*, tile_assign.*, sort.*, prep.*,
                           daemon_rt.*, etc.)
    .kernel_ms_median    — device-side kernel wall (the "OK <ms>" the daemon prints)
  device_profile/classification.json (optional, written by analyze_device_profile.py)
    .classification.fw_max_ms, .classification.overhead_ratio,
    .classification.per_risc_ms, .classification.bound_class
  device_profile/profile_log_device.csv (optional)
    raw per-RISC zone log — re-classified here if classification.json is missing.

Output: <iter_dir>/profile-report.md, plain Markdown for skim-reading.

Bound-class verdict per pipeline stage uses the rule of thumb from
tt-buddy/interpretation.md plus the daemon-specific phase split:

  blend kernel:    overhead_ratio = (kernel_ms_median - device_fw_max) / kernel_ms_median
                     > 40%  → host-dominated (dispatch / transfer)
                     15-40% → mixed
                     < 15%  → device-bound (compute/bandwidth)

  blend daemon_rt: split = (upload_ms + dispatch_ms + readback_ms) / kernel_ms
                   when GSPLAT_PROFILE_PHASES=1 was set; tells you which of
                   the three phases inside the host kernel-window dominates.

For non-blend stages (project / tile_assign / sort) we just report which
sub-step takes the most time so the user knows which Python op to attack.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _read_json(p: Path) -> dict | None:
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def _fmt_ms(ms: float) -> str:
    if ms < 1.0:
        return f"{ms*1000:6.0f} µs"
    return f"{ms:6.2f} ms"


def _pct(part: float, whole: float) -> str:
    if whole <= 0:
        return "  —  "
    return f"{100.0 * part / whole:5.1f}%"


def _classify_blend(kernel_ms: float, fw_max_ms: float) -> tuple[str, float]:
    if kernel_ms <= 0:
        return "unknown", 0.0
    overhead_ratio = (kernel_ms - fw_max_ms) / kernel_ms if kernel_ms else 0.0
    if overhead_ratio > 0.40:
        tag = "host-dominated (dispatch/transfer)"
    elif overhead_ratio > 0.15:
        tag = "mixed"
    else:
        tag = "device-bound (compute or bandwidth)"
    return tag, overhead_ratio


def _build_substage_table(prefix: str, sub_medians: dict[str, float], stage_ms: float) -> list[str]:
    """Return Markdown lines for sub-stages whose key begins with prefix+'.'."""
    keys = sorted([k for k in sub_medians if k.startswith(prefix + ".")])
    if not keys:
        return [f"_no `{prefix}.*` sub-stage timings available_", ""]
    rows = [(k, sub_medians[k]) for k in keys]
    rows.sort(key=lambda kv: -kv[1])
    out = [
        f"| sub-stage                              | wall ms   | % of {prefix:<11} |",
        "|----------------------------------------|-----------|---------------------|",
    ]
    for k, v in rows:
        # Strip the leading "prefix." to keep the table narrow.
        short = k[len(prefix) + 1 :]
        out.append(f"| {short:<38} | {_fmt_ms(v):>9} |        {_pct(v, stage_ms):>5}        |")
    out.append("")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--iter-dir", required=True, type=Path)
    args = ap.parse_args()

    metrics = _read_json(args.iter_dir / "metrics.json")
    if metrics is None:
        print(f"ERROR: no metrics.json in {args.iter_dir}", file=sys.stderr)
        return 2
    cls_json = _read_json(args.iter_dir / "device_profile" / "classification.json")

    stages = metrics.get("stage_medians", {})
    subs = metrics.get("sub_medians", {})
    kernel_ms = metrics.get("kernel_ms_median", 0.0)
    total_ms = stages.get("total_ms", 0.0)

    fw_max_ms = 0.0
    per_risc_ms: dict[str, float] = {}
    legacy_bound = None
    if cls_json:
        cls = cls_json.get("classification", {})
        fw_max_ms = float(cls.get("fw_max_ms", 0.0))
        per_risc_ms = {k: float(v) for k, v in cls.get("per_risc_ms", {}).items()}
        legacy_bound = cls.get("bound_class")

    blend_tag, blend_overhead = _classify_blend(kernel_ms, fw_max_ms)

    lines: list[str] = []
    lines.append(f"# Pipeline profile report — {args.iter_dir.name}")
    lines.append("")
    lines.append(
        "Generated by `scripts/pipeline_profile_report.py`. tt-buddy-style "
        "bound-class signal across all four pipeline stages: project, "
        "tile_assign, sort, blend. Persistent — every iter from "
        "iter-PROF onward emits this report so we don't choose optimization "
        "levers blind."
    )
    lines.append("")

    # ------------------------------------------------------------------
    # Pipeline-wide table.
    # ------------------------------------------------------------------
    lines.append("## Pipeline-wide breakdown")
    lines.append("")
    lines.append("| stage              | wall ms   | % of total | notes                                       |")
    lines.append("|--------------------|-----------|------------|---------------------------------------------|")
    stage_order = ("project", "tile_assign", "sort", "blend")
    for s in stage_order:
        v = stages.get(f"{s}_ms", 0.0)
        note = ""
        if s == "blend":
            note = f"kernel={_fmt_ms(kernel_ms)} ({blend_tag})"
        lines.append(
            f"| {s:<18} | {_fmt_ms(v):>9} | {_pct(v, total_ms):>10} | {note:<43} |"
        )
    lines.append(f"| **total**          | {_fmt_ms(total_ms):>9} | 100.0%     |                                             |")
    lines.append("")

    # ------------------------------------------------------------------
    # Blend kernel — the headline.
    # ------------------------------------------------------------------
    lines.append("## Blend kernel (`blend.daemon_rt.device_kernel`)")
    lines.append("")
    lines.append(f"- host-side wall `kernel_ms_median`: **{_fmt_ms(kernel_ms)}**")
    if fw_max_ms:
        lines.append(f"- device-FW max (max per-RISC FW duration): **{_fmt_ms(fw_max_ms)}**")
        lines.append(f"- overhead ratio: **{100*blend_overhead:5.1f}%** → `{blend_tag}`")
    else:
        lines.append("- no device_profile/classification.json found — re-run with `--profile` to populate.")
    if legacy_bound:
        lines.append(f"- analyze_device_profile classification: `{legacy_bound}`")
    if per_risc_ms:
        lines.append("")
        lines.append("Per-RISC FW duration (median):")
        for risc, ms in sorted(per_risc_ms.items()):
            lines.append(f"  - {risc:<8} = {_fmt_ms(ms)}")
    lines.append("")

    # Daemon-phase split inside kernel_ms (only present if GSPLAT_PROFILE_PHASES=1).
    upload = subs.get("blend.daemon_rt.upload_ms")
    dispatch = subs.get("blend.daemon_rt.dispatch_ms")
    readback = subs.get("blend.daemon_rt.readback_ms")
    io_load = subs.get("blend.daemon_rt.io_load_ms")
    encode = subs.get("blend.daemon_rt.encode_ms")
    io_save = subs.get("blend.daemon_rt.io_save_ms")
    if any(x is not None for x in (upload, dispatch, readback, io_load, encode, io_save)):
        lines.append("### Daemon phases (`blend.daemon_rt.*`)")
        lines.append("")
        lines.append(
            "Phases reported by the C++ daemon. `io_load`, `encode`, `io_save` "
            "are always populated; `upload`, `dispatch`, `readback` only "
            "when the daemon was launched with `GSPLAT_PROFILE_PHASES=1`."
        )
        lines.append("")
        lines.append("| phase           | wall ms   | % of kernel_ms |")
        lines.append("|-----------------|-----------|----------------|")
        for label, val in (
            ("io_load (np.load)", io_load),
            ("encode (lpt+bf16+args)", encode),
            ("upload (6× EnqueueWrite + Finish)", upload),
            ("dispatch (EnqueueMeshWorkload + Finish)", dispatch),
            ("readback (EnqueueRead blocking)", readback),
            ("io_save (np.save)", io_save),
        ):
            if val is None:
                continue
            pct = _pct(val, kernel_ms) if "io_" not in label else "  N/A "
            lines.append(f"| {label:<35} | {_fmt_ms(val):>9} | {pct:>14} |")
        lines.append("")

    # ------------------------------------------------------------------
    # Per-stage sub-step breakdowns.
    # ------------------------------------------------------------------
    for s in stage_order:
        stage_ms = stages.get(f"{s}_ms", 0.0)
        lines.append(f"## `{s}` sub-stages")
        lines.append("")
        lines.extend(_build_substage_table(s, subs, stage_ms))

    # blend.daemon_rt.* (raw including io_load etc — already shown above, but the
    # raw rows live under the daemon_rt sub-stage and we want a full table too).
    if any(k.startswith("blend.daemon_rt.") for k in subs):
        lines.append("## `blend.daemon_rt` sub-stages (all reported phases)")
        lines.append("")
        lines.extend(_build_substage_table("blend.daemon_rt", subs, kernel_ms))

    # ------------------------------------------------------------------
    # Recommended lever family — derived heuristic, not authoritative.
    # ------------------------------------------------------------------
    lines.append("## Recommended lever family (heuristic)")
    lines.append("")
    non_blend = sum(stages.get(f"{s}_ms", 0.0) for s in ("project", "tile_assign", "sort"))
    blend_ms = stages.get("blend_ms", 0.0)
    if non_blend > blend_ms * 0.5:
        lines.append(
            f"- non-blend stages account for {_fmt_ms(non_blend)} = "
            f"{_pct(non_blend, total_ms)} of total. Optimizing only blend "
            "leaves substantial Amdahl headroom unrecovered."
        )
    if blend_overhead > 0.40:
        lines.append(
            "- blend kernel is `host-dominated`: the `device_fw_max` is "
            f"{_fmt_ms(fw_max_ms)} vs host wall {_fmt_ms(kernel_ms)}. "
            "Lever family: batched upload, persistent inputs, Trace API "
            "(post per-frame upload elimination), 2-CQ pipeline. "
            "**Do NOT pursue compute-bound levers (init-fuse, FPU-heavy) "
            "until that gap closes.**"
        )
    elif 0.15 <= blend_overhead <= 0.40:
        lines.append(
            "- blend kernel is `mixed`: both host and device contribute. "
            "Lever family: profile both sides; small wins from each compound."
        )
    elif blend_overhead < 0.15:
        lines.append(
            "- blend kernel is `device-bound`: device_fw_max approaches "
            "host wall. Lever family: compute (init-fuse, async LLK fusion), "
            "reader/writer NoC overlap, math fidelity tuning."
        )
    sort_ms = stages.get("sort_ms", 0.0)
    if sort_ms > total_ms * 0.15:
        lines.append(
            f"- `sort` is {_fmt_ms(sort_ms)} = {_pct(sort_ms, total_ms)} of "
            "total. Current implementation is CPU torch.argsort; if it "
            "dominates, the win is moving sort to device or to a "
            "specialized radix on CPU."
        )
    project_ms = stages.get("project_ms", 0.0)
    if project_ms > total_ms * 0.10:
        lines.append(
            f"- `project` is {_fmt_ms(project_ms)} = {_pct(project_ms, total_ms)} of "
            "total. Sub-stage table above identifies which PyTorch op is the "
            "hot spot (typically `cov3d` or `cov2d` per-Gaussian batched matmuls)."
        )
    lines.append("")
    lines.append(
        "_All numbers are medians over the measured cycles. The verdict "
        "above is a heuristic starting point — confirm with the per-RISC + "
        "sub-stage tables before committing to an iter plan._"
    )

    out_path = args.iter_dir / "profile-report.md"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"[pipeline_profile_report] wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
